version: '3'

services:
  smart-home-server:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - $HOME/data:/app/data
    devices:
      - /dev/ttyACM0
    restart: always
    network_mode: host