version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist
            - package.json
            - yarn.lock
            - pre_deploy.sh
            - post_deploy.sh
  deploy:
    working_directory: ~/project
    docker:
      - image: circleci/node
    steps:
      - attach_workspace:
          at: ~/project
      - add_ssh_keys:
          fingerprints:
            - "25:89:00:e0:02:7f:ff:fb:26:84:ab:b9:6f:c5:1f:8a"
      - run:
          name: Fix host authenticity
          command: |
            ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Stop server
          command: |
            ssh $SSH_USER@$SSH_HOST 'bash -i' < pre_deploy.sh
      - run:
          name: Deploy
          command: |
            scp -r dist package.json yarn.lock $SSH_USER@$SSH_HOST:~/smart-home-server/
      - run:
          name: Start server
          command: |
            ssh $SSH_USER@$SSH_HOST 'bash -i' < post_deploy.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master