const PASSWORDS_ARE_NOT_THE_SAME = "PASSWORDS_ARE_NOT_THE_SAME";
const FIELDS_MISSING = "FIELDS_MISSING";
const USER_NOT_FOUND = "USER_NOT_FOUND";
const INCORRECT_PASSWORD = "INCORRECT_PASSWORD";
const USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS";

module.exports = {
  PASSWORDS_ARE_NOT_THE_SAME,
  FIELDS_MISSING,
  USER_NOT_FOUND,
  INCORRECT_PASSWORD,
  USER_ALREADY_EXISTS
};
