export const PASSWORDS_ARE_NOT_THE_SAME = "PASSWORDS_ARE_NOT_THE_SAME";
export const FIELDS_MISSING = "FIELDS_MISSING";
export const USER_NOT_FOUND = "USER_NOT_FOUND";
export const INCORRECT_PASSWORD = "INCORRECT_PASSWORD";
export const USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS";
